# Site settings
title: Open-klis
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://open-klis.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  open-klis

# Build settings
markdown: kramdown

exclude: ["bundle", "Gemfile", "Gemfile.lock"]
